### ISSUE TITLE
저장소 링크 수정

### ISSUE THREAD

**Issue by Migan178** [devproje/devproje#2]
현재 폐하의 저장소는 Forgejo를 기반으로 한 https://git.wh64.net 이오지만, 폐하께서는 현재로썬 폐쇄되어 쓰지않는 Gitlab을 기반으로 한 https://gitlab.wh64.net 을 사용하고 계시옵니다. 이에 따라 일반 백성들의 혼란이 생길 것으로 예상하여 소신이 직접 상소문을 올리게 되었사옵니다.

**Comment by Migan178** [comment]
폐하, 그나저나 소신의 데스크탑 서버에서의 관직명은 어찌되옵니까?

**Comment by devproje** [comment]
fixed
https://github.com/devproje/devproje/commit/5a842a76facdd2f283b70307e7ca16e8ea298be0
